# Generated by Django 3.1.4 on 2020-12-17 09:04

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_recruitment_applicant', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account.models.MyAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplicant',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('roll_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('batch', models.CharField(choices=[('firstYear', 'First Year'), ('secondYear', 'Second Year'), ('thirdYear', 'Third Year'), ('fourthYear', 'Final Year'), ('PostGraduate', 'PG')], max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electronics and Electrical'), ('MECH', 'Mechanical'), ('CV', 'Civil'), ('CH', 'Chemical'), ('META', 'Metallurgy and Materials')], max_length=20)),
                ('status', models.CharField(choices=[('written', 'Written Test'), ('interview', 'Selected for Interview'), ('selected', 'Selected')], default='written', max_length=20)),
                ('phoneNumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[789]\\d{9}$')])),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('recruitmentYear', models.CharField(default=2020, max_length=4)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
