# Generated by Django 3.1.4 on 2020-12-18 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='batch',
            field=models.CharField(choices=[('firstYear', 'First Year'), ('secondYear', 'Second Year'), ('thirdYear', 'Third Year'), ('fourthYear', 'Final Year'), ('PostGraduate', 'PG')], max_length=20, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electronics and Electrical'), ('MECH', 'Mechanical'), ('CV', 'Civil'), ('CH', 'Chemical'), ('META', 'Metallurgy and Materials')], max_length=20, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[789]\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='status',
            field=models.CharField(choices=[('written', 'Written Test'), ('interview', 'Selected for Interview'), ('selected', 'Selected')], default='written', max_length=20, verbose_name='Status'),
        ),
    ]
