# Generated by Django 3.1.4 on 2020-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201218_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplicant',
            name='application_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='application id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='roll_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
