# Generated by Django 3.1.4 on 2020-12-18 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201218_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandArtRegs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, unique=True, verbose_name='Team Name')),
                ('college', models.CharField(max_length=50, verbose_name='College/University Name')),
                ('mem1', models.CharField(max_length=30, verbose_name='First Member Name')),
                ('mem2', models.CharField(blank=True, max_length=30, verbose_name='Second Member Name')),
                ('mem3', models.CharField(blank=True, max_length=30, verbose_name='Third Member Name')),
                ('mem4', models.CharField(blank=True, max_length=30, verbose_name='Fourth Member Name')),
                ('mem5', models.CharField(blank=True, max_length=30, verbose_name='Fifth Member Name')),
                ('mem6', models.CharField(blank=True, max_length=30, verbose_name='Sixth Member Name')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[789]\\d{9}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('event', models.CharField(choices=[('Engineer', 'Engineer'), ('Incident', 'Incident'), ('Major Project', 'Major Project')], max_length=20, verbose_name='event')),
                ('roll_number', models.CharField(max_length=9, unique=True, verbose_name='Roll Number')),
                ('hostel_block', models.CharField(choices=[('First Block', 'First Block'), ('Second Block', 'Second Block'), ('Third Block', 'Third Block'), ('Fourth Block', 'Fourth Block'), ('Fifth Block', 'Fifth Block'), ('Seventh Block', 'Seventh Block'), ('Mega Tower 1', 'Mega Tower 1'), ('Mega Tower 2', 'Mega Tower 2'), ('Mega Tower 3', 'Mega Tower 3'), ('GH1', 'GH1'), ('GH3', 'GH3'), ('GH4', 'GH4'), ('GH5', 'GH5')], max_length=30)),
                ('batch', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('final_year', 'Final Year'), ('pg', 'PG')], default='firstYear', max_length=20, verbose_name='Batch')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[789]\\d{9}$')], verbose_name='Phone Number')),
            ],
        ),
    ]
