# Generated by Django 3.1.4 on 2020-12-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_sandartregs_volunteers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SandArtRegs',
            new_name='SandArtReg',
        ),
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
