# Generated by Django 3.1.4 on 2020-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201218_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='event',
            field=models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Incident', 'Incident'), ('Major Project', 'Major Project')], max_length=20, verbose_name='event'),
        ),
    ]
