# Generated by Django 3.1.4 on 2021-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201219_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentapplicant',
            name='recruitmentYear',
            field=models.CharField(default=2021, max_length=4),
        ),
    ]
