# Generated by Django 3.0.5 on 2020-06-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='page_to_display',
            field=models.IntegerField(default=0),
        ),
    ]
