# Generated by Django 3.0.5 on 2020-06-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200605_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('art_filter', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('art_img', models.ImageField(upload_to='images/art')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_posts', to='mysite.Member')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
