# Generated by Django 3.0.5 on 2020-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='testimonial',
            field=models.TextField(default=' '),
        ),
    ]
