# Generated by Django 3.1.2 on 2020-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_event_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='images/blogs'),
        ),
    ]
