# Generated by Django 2.2.12 on 2020-12-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_event_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_image', models.ImageField(upload_to='images/art')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(upload_to='images/blog')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/event')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(upload_to='images/gallery')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='small_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='linkdin',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='art',
            name='art_filter',
        ),
        migrations.RemoveField(
            model_name='art',
            name='art_img',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bg_img',
        ),
        migrations.RemoveField(
            model_name='event',
            name='page_to_display',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_posts', to='mysite.Event'),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='mysite.Blog'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_posts', to='mysite.Art'),
        ),
    ]
