# Generated by Django 2.2.13 on 2020-10-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_event_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(default='None', upload_to='images/blogs'),
            preserve_default=False,
        ),
    ]
