# Generated by Django 2.2.12 on 2020-12-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20201217_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='images/blog'),
        ),
    ]
