# Generated by Django 2.2.13 on 2020-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20201001_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='udaan_event',
            name='event_description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udaan_event',
            name='event_img',
            field=models.ImageField(default='None', upload_to='images/udaan/events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udaan_event',
            name='event_name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
