# Generated by Django 2.2.13 on 2020-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20201002_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udaan_static',
            name='bg_pic',
        ),
    ]
