# Generated by Django 2.2.13 on 2020-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20201002_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='udaan_static',
            name='insta_keyword',
            field=models.CharField(default='AJ', max_length=50),
            preserve_default=False,
        ),
    ]
