# Generated by Django 3.1.4 on 2020-12-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20201217_1241'),
        ('mysite', '0010_remove_udaan_static_bg_pic'),
    ]

    operations = [
    ]
