# Generated by Django 3.1.4 on 2020-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_merge_20201221_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_type',
            field=models.CharField(choices=[('Sketches', 'Sketches'), ('Doodles', 'Doodles'), ('Abstract', 'Abstract'), ('Portrait', 'Portrait'), ('Nature', 'Nature'), ('Digital', 'Digital')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
