# Generated by Django 3.1.4 on 2020-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_art_art_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_type',
            field=models.CharField(choices=[('Sketches', 'Sketches'), ('Doodles', 'Doodles'), ('Abstract', 'Abstract'), ('Portrait', 'Portrait'), ('Nature', 'Nature'), ('Digital', 'Digital'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
