# Generated by Django 3.1.4 on 2020-12-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_art_art_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtImage',
        ),
    ]
