# Generated by Django 3.1.4 on 2020-12-21 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_delete_artimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_on',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 21, 13, 15, 172966, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='resources',
            field=models.CharField(blank=True, max_length=100, verbose_name='Event Resources'),
        ),
    ]
