# Generated by Django 3.1.4 on 2020-12-22 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20201222_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 11, 45, 35, 742110, tzinfo=utc)),
        ),
    ]
