# Generated by Django 3.1.4 on 2020-12-23 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20201223_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 11, 19, 24, 572143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
