# Generated by Django 3.1.4 on 2020-12-23 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20201223_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='member',
            name='batch',
            field=models.CharField(default='2020', help_text='passing year', max_length=4, verbose_name='batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 19, 30, 47, 395441, tzinfo=utc)),
        ),
    ]
