# Generated by Django 3.1.2 on 2020-12-30 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20201229_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 18, 41, 54, 324028, tzinfo=utc)),
        ),
    ]
