# Generated by Django 3.1.4 on 2021-01-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20210101_1742'),
        ('mysite', '0024_auto_20201229_1548'),
    ]

    operations = [
    ]
