# Generated by Django 3.1.4 on 2021-01-06 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20210101_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 7, 25, 48, 286180, tzinfo=utc)),
        ),
    ]
