# Generated by Django 3.1.4 on 2021-01-06 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20210106_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='head',
        ),
        migrations.AddField(
            model_name='member',
            name='curr_core',
            field=models.BooleanField(default=False, help_text='Is this member current core member?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 10, 56, 0, 48100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='batch',
            field=models.CharField(help_text='passing year', max_length=4, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='member',
            name='insta',
            field=models.URLField(blank=True, verbose_name='Instagram profile URL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(blank=True, help_text='Enter for past postholders also. ex, <batch> Convener for a past batch convener', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='testimonial',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
