# Generated by Django 3.1.4 on 2021-01-06 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_auto_20210106_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-batch', '-member_name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 11, 38, 16, 71552, tzinfo=utc)),
        ),
    ]
