# Generated by Django 3.1.4 on 2021-01-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20201230_1841'),
        ('mysite', '0030_auto_20210106_1733'),
    ]

    operations = [
    ]
