# Generated by Django 3.1.4 on 2021-01-18 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_merge_20210108_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 15, 35, 8, 465845, tzinfo=utc)),
        ),
    ]
