# Generated by Django 3.1.4 on 2021-01-18 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_auto_20210118_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 15, 50, 23, 230752, tzinfo=utc)),
        ),
    ]
