# Generated by Django 3.1.4 on 2021-01-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_auto_20210101_1849'),
        ('mysite', '0033_auto_20210118_1550'),
    ]

    operations = [
    ]
