# Generated by Django 3.1.4 on 2021-03-22 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_auto_20210322_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-batch', '-member_name', '-post']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 15, 45, 55, 760703, tzinfo=utc)),
        ),
    ]
