# Generated by Django 3.1.4 on 2021-03-22 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0039_auto_20210322_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 15, 46, 53, 959174, tzinfo=utc)),
        ),
    ]
