# Generated by Django 3.1.4 on 2021-03-22 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_auto_20210322_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udaan_description', models.TextField()),
                ('udaan_date', models.DateTimeField(null=True)),
                ('recs_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Udaan_static',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['batch', 'member_name', 'post']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 18, 22, 37, 315643, tzinfo=utc)),
        ),
    ]
