# Generated by Django 3.1.4 on 2021-03-22 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0041_auto_20210322_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 18, 25, 38, 703622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='recs_date',
            field=models.DateField(null=True),
        ),
    ]
