# Generated by Django 3.1.4 on 2021-03-22 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_auto_20210322_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 18, 25, 52, 714968, tzinfo=utc)),
        ),
    ]
