# Generated by Django 3.1.4 on 2021-03-22 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0044_auto_20210322_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='recs_form',
            field=models.BooleanField(default=False, help_text='Check if we recruitments form is to be displayed', verbose_name='Recruitment form open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 18, 31, 6, 672432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='sand_art_form',
            field=models.BooleanField(default=False, help_text='Check if Sand Art Competition form is to be displayed.', verbose_name='Sand Art Competion form open'),
        ),
    ]
